name: Daily VIX Data Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: write

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance

      - name: Run the data fetcher
        run: python scraper.py
      
      - name: Commit and push if data changed
        run: |
          git config --global user.name "VIX Data Bot"
          git config --global user.email "bot@github.com"
          git add vix_data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update VIX data for $(date -u +'%Y-%m-%d')" && git push)
